### ISSUE TITLE
handle quotations marks in serialized JSON strings

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#14]
#### Description:

#xsd does not allow quotations marks within a string. 

#### Steps to reproduce:

We need to find a way to encode it differently. One way would be to replace every quotation mark with a hash in the serialized JSON datatype.

#### Expected behaviour:

something like this works for example:
`:BH.oM.Base.BHoMObject.CustomData "{##nxn2xipevdn#:{##type#:#BH.oM.Geometry.Point, Geometry_oM#,#X#:0.921321943365653,#Y#:0.54057410198290556,}"^^:BH.oM.RDF.JsonSerialized.`

**Comment by DiellzaElshani** [comment]
suggestion from Daniel: 

**When you write a JSON file you have to scape the strings. This means writing \". The issue is that you can also have a \" into a string that corresponds to a value in JSON. Don't reinvent the wheel, use a JSON library to serialize and read json strings. If you have a JSON document, then write it to a string. Then convert this string into a JSON string and serialize it again. This serialization is the same that is used in RDF. You can do the same when reading the string.**

**Comment by alelom** [comment]
Hey @DiellzaElshani , have you seen my proposal above? Solution (2) has the advantage of being robust, but I realized that on the other hand the Json representation will end up being non-readable by humans, since it will be encoded. The json representation will be always de-serializable when you want to get the object back.

Do we need to keep the JsonRepresentation readable by humans? If so, the solution will become more complex and we will need to consider Solution (1) somehow.

**Comment by DiellzaElshani** [comment]
I think (2) can be a good option. And as you mention, it won't be readable by humans, thus also not possible to be used to infer knowledge. But, the fact that we can decode it and get back the object is good enough. 
Solution (1): Even if we replace the """ with something and read the JSON string, it is not adding much value, I think (?). We can read it, but we can't do much with it anyway, right?
Solution (2): At the moment, I can't think of what can be a drawback of encoding the string in Base64; it sounds like a good solution. 
In terms of reasoning in both cases, we can check if the string is equal/identical. 

I suggest that we try to avoid the JSON serialized string whenever we can, and if we need to use it we go for solution (2).

**Comment by alelom** [comment]
> Solution (1): Even if we replace the """ with something and read the JSON string, it is not adding much value, I think (?). We can read it, but we can't do much with it anyway, right?

It would be deserializable just like solution (2). Replacing the characters is still a form of encoding, but unlike base64 it's more cumbersome and less reliable.

Solution (2) it is then!

**Comment by alelom** [comment]
We should ask, how would "serializing the Json twice" remove the problem with the quotation marks problem?

The Ruby script there is actually "serializing" three times, because it starts from a Json object already, then it serializes it twice. 
What the script does of useful is this: the first `to_json()` call of the already serialized object returns the same string but with _escaped_ quotes. The second `to_json()` call is redundant and in fact removing it returns the same result. 

I think that Daniel's idea is that by serializing the Json twice you get the quotes to be escaped. That is not true for all serializers. It may be true for this one in Ruby, but I don't know of any others that do it, certainly not in C#. Here's a live fiddle that "serializes twice" a C# object, and the quotes are not escaped: https://dotnetfiddle.net/2dFSly

Escaping json symbols is not trivial: https://stackoverflow.com/questions/1242118/how-to-escape-json-string

Additionally, escaping could not be the solution anyway. We are not having a problem with deserialization of the serialized text. We have the problem of how TTL parsers interpret the serialized text. Escaping the Json may not solve this latter problem, because I personally do not know what TTL parsers understand as an escaping symbol.

So I still think the base64 encoding is probably better for now.
