### ISSUE TITLE
Implement search of files on FileSystem corresponding to BHoM types to obtain their correct URL

### ISSUE THREAD

**Issue by alelom** [BHoM/RDF_Prototypes#2]
#### Description:

Right now we are relying on namespace compliance to obtain the URL of BHoM Types.

This actually fails in several places: for example, the folder/subfolder rule is not respected for most Geometry_oM types.

Instead, we can rely on repos downloaded on the FileSystem to find the corresponding URL online.

**Comment by FraserGreenroyd** [comment]
@alelom I like this, I wonder if it's worth putting a method in a core engine (Data Engine? Base Engine?) to take an ending file path and generate the URL?

Only reason I suggest that is because I can see BHoMBot getting some use from such a method too in the future to aid with compliance reports/links, etc. Equally the API stuff might benefit to it.

Then this toolkit could implement the searching mechanism, but generating the actual URL could be handled by a central method for other uses? Then BHoMBot can implement its own searching algorithm too but get the URL centrally.

Just a thought - obviously happy for you to ignore this if it's quicker to just do it all on this repo for now 😄

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/RDF_Prototypes/commit/bc875adc6c7b08d874097aff79ed54131dc87da0
