### ISSUE TITLE
Visualize the graph in real time

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#26]
#### Description:

Visualizing the graph is sometimes the most impressive and catchy part of the work. Therefore, I'd suggest that we also need to chose a graph visualizer. We can think of a graph database that can read our ttl file in real time and visualize it (with instances).

Id suggest something opensource and web based. I will research some options in the upcoming days. I assume our prior feature requests would be ability to: (1) visualize the graph, (2) allow SPARQL queries; (3) if possible allow reasoning and data validation too (meaning that it allows us to add also SHACL shape graphs). 

![image](https://user-images.githubusercontent.com/50298535/171037437-91319bf3-038f-4cd9-87e3-ed2cb044d17b.png)

One way to go would be to use the GraphDB platform. The graphBD platform allows also querying the graph and working with the data. 

@danielhz feel free to suggest something.

**Comment by DiellzaElshani** [comment]
@danielhz I think D3 is a good way to start. Apparently also a colleague here at ICD is using it. I would imagine that we can call D3 directly from Rhino/Grasshopper, and visualize the graph in real time within Rhino/Grasshopper.

**Comment by alelom** [comment]
Hey guys, just some warning on D3.js. We did use D3 for some advanced visualisations in BHoM, but I believe that its use was most successful when we used it to make proper web pages rather than on-the-go visualisations. D3 is a complicated beast, even more so to interoperate with another non-frontend (i.e. not for HTML web pages) language like C#. To create a D3 graph, you need first to obtain a matrix of raw data to feed to a function that creates the graph. So, in addition to the infrastructure that creates the graph, we'd need to serialize our TTL graph (or, better, its backend generator CSharpGraph) into a raw data format digestible by D3. This alone is a challenge. Then, there is the actual graph creation in D3. D3 is meant for advanced data visualisation _for web frontends_, so it is mostly designed to work with the DOM (the HTML). This makes it an excellent tool for advanced data visualisation on web pages, but exceedingly complicated (and, I personally would add, awful) for anything else. If the aim is data visualisation, and there is no constraint to build an HTML page, my personal opinion is that literally anything is better than D3. For example, in statistical analysis, you would use libraries like MatPlotLib to visualise whatever you are doing; you would use D3 only after finishing your study, in case you want to publish it on the web. I think it is very easy to underestimate how difficult D3 is, especially for non web developers.

Because we are working in .NET and not in frontend webdev, a first simple approach would be to look at .NET libraries for data visualisation. Because I don't suppose there are many of them, or of great quality, if we end up unsatisfied we could then look at alternatives, including D3 if nothing simpler can be found. A good enough starting point could be to look at [GraphViz](http://www.graphviz.org/), which includes a variety of tools for non-frontend languages. From a quick search I found a [.NET (C#) wrapper for it](https://github.com/Rubjerg/Graphviz.NetWrapper).

**Comment by DiellzaElshani** [comment]
If GraphDB has what we need, I see that the source code of their visualizations is open in D3 libraries. https://observablehq.com/@d3/gallery. 
I still think D3 could be a good way to go. Let's give it a try. We can talk next week about this.

**Comment by DiellzaElshani** [comment]
Check out this approach for visualizing and querying the graph: 
https://lbd-hackers.github.io/slides/20221116_BILT.html#/11/1
![viyualization](https://user-images.githubusercontent.com/50298535/204599630-31836492-0f42-4ba1-816b-6d9fd87c0f83.gif)

**Comment by DiellzaElshani** [comment]
I tried again the connection to Graph DB, 

**What works for me:** 
- Opening GraphDB 
- Deleting a repository in GraphDB 

**What doesn't work:** 
- Create a repository, 
- Post the graph to the repository, 
- Update the graph on the repository. 



![image](https://user-images.githubusercontent.com/50298535/225873470-d566aa84-2987-42ad-95fd-01d1ea6a0586.png)

**Comment by alelom** [comment]
Hey @DiellzaElshani , thanks for this, but this issue was a feature issue which was closed because the feature was added. When you discover a problem with a feature, please raise an appropriate bug issue. Issues are also used to measure progress, we can't reopen old ones that were addressed if bugs are found. Could you please delete your last comment and move its content to a new bug issue?
